### ISSUE TITLE
Les noms de fichier ne sont pas normalisés

### ISSUE THREAD

**Issue by Plou** [Gregcop1/in_gallery#10]
Si le nom d'un fichier contient une apostrophe, une erreur de syntaxe est provoqué dansla requête SQL

**Comment by Gregcop1** [comment]
Cette erreur n'arrive qu'en créant les dossiers et fichiers à la main. En passant par le back de typo, les noms des fichiers et dossiers sont corrigés. En utilisation réelle, ce bug n'est donc pas réellement possible.
